# Generated by Django 5.1 on 2024-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(choices=[('temperature', 'Temperature'), ('vibration', 'Vibration')], max_length=20)),
                ('EventValue', models.FloatField()),
                ('EventDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
